version: '3'

services:
  db:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "5433:5432"
  web:
    build: .
    command: python app.py
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DBNAME: "${POSTGRES_DBNAME}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
  migration:
    build: .
    command: python migrate.py
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DBNAME: "${POSTGRES_DBNAME}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - .:/code
    depends_on:
      - db
